name: model_railway
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python==3.11.5
  - pip==23.3.1
  - pip:
    - numpy==2.1.3
    - pygame==2.6.0
    - pyopengl==3.1.7
